from __future__ import annotations

from typing import Protocol

from ..models import LaunchAttempt, ProviderState


class ProviderAdapter(Protocol):
    def identity_for(self, job_id: str, task_name: str, generation: int, attempt_id: str) -> str: ...
    def preflight(self) -> dict: ...
    def launch(self, attempt: LaunchAttempt, *, supervisor_url: str, attempt_token: str) -> dict: ...
    def status(self, provider_ref: str) -> ProviderState: ...
    def output(self, provider_ref: str) -> str: ...
