from __future__ import annotations

import json
import re
import subprocess
import tempfile
from pathlib import Path
from typing import Any

from ..models import LaunchAttempt, ProviderState


class KaggleProvider:
    """Real Kaggle CLI adapter. Stop is cooperative through the DAEP worker; kernels are never deleted as a stop primitive."""

    def __init__(self, *, username: str, command: str = "kaggle", timeout_seconds: int = 120):
        if not username:
            raise ValueError("Kaggle username is required")
        self.username = username
        self.command = command
        self.timeout_seconds = timeout_seconds

    @staticmethod
    def _slug(value: str, limit: int = 36) -> str:
        value = re.sub(r"[^a-z0-9-]+", "-", value.lower()).strip("-")
        return (value or "daep")[:limit].rstrip("-")

    def identity_for(self, job_id: str, task_name: str, generation: int, attempt_id: str) -> str:
        short = attempt_id.removeprefix("att_")[:8]
        slug = self._slug(f"daep-{job_id[-8:]}-{task_name[:16]}-g{generation}-{short}", 48)
        return f"{self.username}/{slug}"

    def _run(self, args: list[str], *, cwd: Path | None = None, timeout: int | None = None) -> subprocess.CompletedProcess[str]:
        return subprocess.run(
            [self.command, *args],
            cwd=cwd,
            text=True,
            capture_output=True,
            timeout=timeout or self.timeout_seconds,
            check=False,
            env=None,
        )

    def preflight(self) -> dict[str, Any]:
        result = self._run(["kernels", "list", "--page-size", "1"])
        if result.returncode != 0:
            raise RuntimeError(f"Kaggle CLI preflight failed: {(result.stderr or result.stdout)[-1200:]}")
        return {"provider": "kaggle", "username": self.username, "cli_ok": True}

    def _kernel_files(
        self,
        directory: Path,
        attempt: LaunchAttempt,
        *,
        supervisor_url: str,
        attempt_token: str,
    ) -> None:
        owner, slug = attempt.provider_ref.split("/", 1)
        runtime_url = f"{supervisor_url.rstrip('/')}/v1/worker/{attempt.id}/runtime"
        kernel = f'''# Generated by my-daep. Kernel is private; credential is attempt-scoped.
import os
import urllib.request

os.environ["DAEP_SUPERVISOR_URL"] = {supervisor_url!r}
os.environ["DAEP_ATTEMPT_ID"] = {attempt.id!r}
os.environ["DAEP_ATTEMPT_TOKEN"] = {attempt_token!r}
req = urllib.request.Request(
    {runtime_url!r},
    headers={{"Authorization": "Bearer " + os.environ["DAEP_ATTEMPT_TOKEN"]}},
)
with urllib.request.urlopen(req, timeout=30) as response:
    source = response.read().decode("utf-8")
exec(compile(source, "daep_worker_bundle.py", "exec"), {{"__name__": "__main__"}})
'''
        (directory / "kernel.py").write_text(kernel, encoding="utf-8")
        metadata = {
            "id": f"{owner}/{slug}",
            "title": f"DAEP {attempt.job_id[-8:]} {attempt.task_name} g{attempt.generation}",
            "code_file": "kernel.py",
            "language": "python",
            "kernel_type": "script",
            "is_private": True,
            "enable_gpu": False,
            "enable_internet": True,
            "dataset_sources": [],
            "competition_sources": [],
            "kernel_sources": [],
        }
        (directory / "kernel-metadata.json").write_text(json.dumps(metadata, indent=2), encoding="utf-8")

    def launch(self, attempt: LaunchAttempt, *, supervisor_url: str, attempt_token: str) -> dict[str, Any]:
        with tempfile.TemporaryDirectory(prefix="daep-kaggle-") as temp:
            directory = Path(temp)
            self._kernel_files(directory, attempt, supervisor_url=supervisor_url, attempt_token=attempt_token)
            result = self._run(["kernels", "push", "-p", str(directory)], timeout=max(self.timeout_seconds, 180))
            output = (result.stdout + "\n" + result.stderr).strip()
            if result.returncode != 0:
                raise RuntimeError(f"kaggle kernels push failed: {output[-2000:]}")
            return {"provider_ref": attempt.provider_ref, "output": output[-2000:]}

    def status(self, provider_ref: str) -> ProviderState:
        result = self._run(["kernels", "status", provider_ref])
        raw = (result.stdout + "\n" + result.stderr).strip()
        lower = raw.lower()
        if result.returncode != 0:
            if "404" in lower or "not found" in lower:
                return ProviderState("NOT_FOUND", raw=raw, terminal=False, succeeded=False)
            return ProviderState("UNKNOWN", raw=raw, terminal=False, succeeded=False)
        if any(word in lower for word in ("complete", "completed")):
            return ProviderState("COMPLETE", raw=raw, terminal=True, succeeded=True)
        if any(word in lower for word in ("error", "failed")):
            return ProviderState("ERROR", raw=raw, terminal=True, succeeded=False)
        if any(word in lower for word in ("running", "queued", "pending")):
            return ProviderState("RUNNING", raw=raw, terminal=False, succeeded=False)
        return ProviderState("UNKNOWN", raw=raw, terminal=False, succeeded=False)

    def output(self, provider_ref: str) -> str:
        with tempfile.TemporaryDirectory(prefix="daep-kaggle-output-") as temp:
            result = self._run(["kernels", "output", provider_ref, "-p", temp], timeout=max(self.timeout_seconds, 180))
            if result.returncode != 0:
                return (result.stdout + "\n" + result.stderr).strip()[-4000:]
            chunks: list[str] = []
            for path in sorted(Path(temp).rglob("*")):
                if path.is_file() and path.stat().st_size <= 2_000_000:
                    try:
                        chunks.append(f"\n--- {path.name} ---\n{path.read_text(encoding='utf-8', errors='replace')}")
                    except OSError:
                        pass
            return "".join(chunks)[-20_000:]
